/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccessTokens: () => import('#features/auth/controllers/access_tokens_controller'),
    NewAccount: () => import('#features/auth/controllers/new_account_controller'),
  },
  profile: {
    Profile: () => import('#features/profile/controllers/profile_controller'),
  },
  recipes: {
    Recipes: () => import('#features/recipes/controllers/recipes_controller'),
  },
}
